import { Router } from "express";
import authRouter from "../modules/auth/AuthRouter.js";
import userRouter from "../modules/user/UserRouter.js";
import transactionRouter from "../modules/transaction/TransactionRouter.js";
import categoryRouter from "../modules/category/CategoryRouter.js";
import budgetRouter from "../modules/budget/BudgetRouter.js";
import goalRouter from "../modules/goal/GoalRouter.js";
import analyticsRouter from "../modules/analytics/AnalyticsRouter.js";
import notificationRouter from "../modules/notification/NotificationRouter.js";
const router = Router();
router.use("/auth", authRouter);
router.use("/users", userRouter);
router.use("/transactions", transactionRouter);
router.use("/categories", categoryRouter);
router.use("/budgets", budgetRouter);
router.use("/goals", goalRouter);
router.use("/analytics", analyticsRouter);
router.use("/notifications", notificationRouter);
export default router;
